In [ ]:
# Name : Kubra Iqbal
#Honor code : I have not given or received any unauthorized assistance on this assignment.”  


In [2]:
import numpy as np #part 1

In [4]:
a = np.arange(0, 100, 1) #part 2

In [5]:
b = np.arange(0, 100, 10) # part 3

In [6]:
c = np.linspace(0, 10, 101, endpoint=True) # part 4

In [7]:
d = np.random.randint(0,10000,100).reshape(10,10) #part 5

In [8]:
a = a.reshape(10,10) #part 6

In [9]:
a[4,5] #part 7

45

In [10]:
a[4] #part 8

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
d.sum() #part 9

500520

In [16]:
b.transpose() # part 11

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
a + d # part 12

array([[5842, 7786, 1651, 5416,  117, 2086, 7355, 7372, 6733,   37],
       [1263, 3480, 5104, 1244, 5412, 7838, 3368, 2966, 6288, 8235],
       [7187,  704,  180, 9587, 3935, 6501, 8579, 4489, 3765,  362],
       [3446, 4707, 6307, 8940, 7870, 9578,  528, 6791, 3250, 8647],
       [1561, 2217, 6079, 8935, 9589, 1455, 6224, 1740, 2661, 4893],
       [6007, 5028, 6303, 9168, 8678, 5279, 9502, 5450, 4124, 8838],
       [9951, 1881, 1435, 5179, 3119, 8208, 3942, 7859, 3685, 4360],
       [2284, 3682,  294, 3317, 5556, 5898, 4255, 6566,  515, 4556],
       [2054, 8013, 2624, 7947, 7704, 5948, 1823, 8987, 1649, 8746],
       [5361, 5586, 1687, 2420, 7052, 9634, 7055, 8407, 4024, 3530]])

In [14]:
a * d #part 12

array([[     0,   7785,   3298,  16239,    452,  10405,  44094,  51555,
         53800,    252],
       [ 12530,  38159,  61104,  16003,  75572, 117345,  53632,  50133,
        112860, 156104],
       [143340,  14343,   3476, 219972,  93864, 161900, 222378, 120474,
        104636,   9657],
       [102480, 144956, 200800, 293931, 266424, 334005,  17712, 249898,
        122056, 335712],
       [ 60840,  89216, 253554, 382356, 419980,  63450, 284188,  79571,
        125424, 237356],
       [297850, 253827, 325052, 483095, 465696, 287320, 528976, 307401,
        235828, 517961],
       [593460, 111020,  85126, 322308, 195520, 529295, 255816, 522064,
        245956, 296079],
       [154980, 256381,  15984, 236812, 405668, 436725, 317604, 499653,
         34086, 353683],
       [157920, 642492, 208444, 652712, 640080, 498355, 149382, 774300,
        137368, 770473],
       [474390, 500045, 146740, 216411, 654052, 906205, 668064, 806070,
        384748, 339669]])

In [17]:
a.dot(a*d) #part 14

array([[ 12517750,  14228840,   6920788,  16043566,  20090876,  21509090,
         15298912,  22975049,   8645150,  18194843],
       [ 32495650,  34811080,  19956568,  44441956,  52263956,  54959140,
         40717372,  57586239,  24212770,  48364303],
       [ 52473550,  55393320,  32992348,  72840346,  84437036,  88409190,
         66135832,  92197429,  39780390,  78533763],
       [ 72451450,  75975560,  46028128, 101238736, 116610116, 121859240,
         91554292, 126808619,  55348010, 108703223],
       [ 92429350,  96557800,  59063908, 129637126, 148783196, 155309290,
        116972752, 161419809,  70915630, 138872683],
       [112407250, 117140040,  72099688, 158035516, 180956276, 188759340,
        142391212, 196030999,  86483250, 169042143],
       [132385150, 137722280,  85135468, 186433906, 213129356, 222209390,
        167809672, 230642189, 102050870, 199211603],
       [152363050, 158304520,  98171248, 214832296, 245302436, 255659440,
        193228132, 265253379, 1176184

In [18]:
np.amax(a) # part 10 -- it is in the end because i didn't know how to add it on the top on the jypyter notebook, initially missed this part

99